-- Enable UUID generation
create extension if not exists "uuid-ossp";

-- Leads: public can insert (contact form), only service_role can read
create table if not exists public.leads (
  id uuid primary key default uuid_generate_v4(),
  name text,
  email text,
  phone text,
  company text,
  message text,
  source text,
  created_at timestamptz default now()
);
alter table public.leads enable row level security;
drop policy if exists "leads_insert_anon" on public.leads;
create policy "leads_insert_anon" on public.leads
  for insert
  to anon
  with check (true);
drop policy if exists "leads_select_service" on public.leads;
create policy "leads_select_service" on public.leads
  for select
  to service_role
  using (true);

-- Services
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  blurb text,
  icon_url text,
  sort_order int
);
alter table public.services enable row level security;
drop policy if exists "services_read_all" on public.services;
create policy "services_read_all" on public.services
  for select
  to anon, authenticated
  using (true);

-- Projects
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  excerpt text,
  body_md text,
  cover_url text,
  gallery jsonb,
  tags text[],
  featured boolean default false
);
alter table public.projects enable row level security;
drop policy if exists "projects_read_all" on public.projects;
create policy "projects_read_all" on public.projects
  for select
  to anon, authenticated
  using (true);

-- Testimonials
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text,
  role text,
  company text,
  quote text,
  avatar_url text
);
alter table public.testimonials enable row level security;
drop policy if exists "testimonials_read_all" on public.testimonials;
create policy "testimonials_read_all" on public.testimonials
  for select
  to anon, authenticated
  using (true);

-- Nav
create table if not exists public.nav_links (
  id bigint generated by default as identity primary key,
  zone text check (zone in ('header','footer')) default 'header',
  label text not null,
  href text not null,
  link_order int
);
alter table public.nav_links enable row level security;
drop policy if exists "nav_read_all" on public.nav_links;
create policy "nav_read_all" on public.nav_links
  for select
  to anon, authenticated
  using (true);

-- Pages (for hero/homepage copy)
create table if not exists public.pages (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  hero_title text,
  hero_sub text,
  hero_image_url text,
  cta_text text,
  cta_href text
);
alter table public.pages enable row level security;
drop policy if exists "pages_read_all" on public.pages;
create policy "pages_read_all" on public.pages
  for select
  to anon, authenticated
  using (true);

-- Badges/Certs
create table if not exists public.badges (
  id bigint generated by default as identity primary key,
  logo_url text not null,
  alt text,
  href text,
  sort_order int
);
alter table public.badges enable row level security;
drop policy if exists "badges_read_all" on public.badges;
create policy "badges_read_all" on public.badges
  for select
  to anon, authenticated
  using (true);

-- Seed minimal content
insert into public.nav_links (zone, label, href, link_order) values
  ('header','Services','/#services', 1),
  ('header','Projects','/projects', 2),
  ('header','Testimonials','/#testimonials', 3),
  ('header','Contact','/contact', 4),
  ('footer','Privacy','/privacy', 1),
  ('footer','Contact','/contact', 2)
on conflict do nothing;

insert into public.pages (slug, hero_title, hero_sub, hero_image_url, cta_text, cta_href) values
 ('home','Precision fabrication for aerospace & high‑tech','CNC, sheet metal, and rapid prototyping trusted by demanding teams.','/media/hero/default.jpg','Request a quote','/contact')
on conflict (slug) do nothing;

insert into public.services (title, blurb, icon_url, sort_order) values
 ('CNC Machining','Tight‑tolerance 3‑/5‑axis milling & turning for production or R&D.','/media/icons/cnc.svg',1),
 ('Sheet Metal','Laser cutting, bending, and finishing for enclosures and brackets.','/media/icons/sheetmetal.svg',2),
 ('Rapid Prototyping','Fast iterations in aluminum, steel, and composites.','/media/icons/prototype.svg',3)
on conflict do nothing;

insert into public.projects (title, slug, excerpt, body_md, cover_url, featured, tags) values
 ('Flight‑qualified bracket','flight-qualified-bracket','Lightweight, high‑stiffness bracket fabricated under aerospace QA.','## Overview\n\nThis part demonstrates lightweighting, tolerance controls, and QA suitable for flight hardware.','/media/projects/flight-bracket.jpg', true, array['aerospace','cnc'])
on conflict (slug) do nothing;

insert into public.testimonials (name, role, company, quote, avatar_url) values
 ('A. Rivera','Mechanical Lead','Orbital Systems','They hit our tolerance window and deadline.','/media/avatars/rivera.jpg')
on conflict do nothing;

insert into public.badges (logo_url, alt, href, sort_order) values
 ('/media/badges/iso.svg','ISO Certified','#',1),
 ('/media/badges/as9100.svg','AS9100','#',2),
 ('/media/badges/itarm.svg','ITAR','#',3)
on conflict do nothing;
